---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service1
  
  tags:
    - java
    - gradle

spec:
  type: service
  owner: group:credit
  lifecycle: production
  system: OCS
  providesApis:
    - api1
  #   - api2
  # consumesApis:
  #   - api3
  # dependsOn:
  #   - resource:db1
  #   - component:componnet1
---
apiVersion: backstage.io/v1alpha1
kind: Api
metadata:
  name: api1
spec:
  type: openapi
  owner: Component: service1
  lifecycle: production
  system: OCS
 definition: |
   syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
