---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service1
  
  tags:
    - java
    - gradle

spec:
  type: service
  owner: group:credit
  lifecycle: production
  system: OCS
  providesApis:
    - api1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api1
spec:
  type: openapi
  owner: 
    Component: service1
  lifecycle: production
  system: OCS
  definition: |
     syntax = "proto3";

---
